In [3]:
from transformers import pipeline

In [7]:
pipe = pipeline(task="text-generation",model="gpt2")

Device set to use mps:0


In [33]:
# pipe??

In [9]:
prompt = """you are an assistant. exptract the bullet points from the following paragraph.
paragraph:"Machine Learning is a technique that allows computers to learn from data and make decisions without explicit programming. It works by identifying patterns in data and using them to make predictions"
Bullets:
"""

In [15]:
gen_text = pipe(prompt,max_new_tokens=20)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [23]:
print(gen_text[0]["generated_text"])

you are an assistant. exptract the bullet points from the following paragraph.
paragraph:"Machine Learning is a technique that allows computers to learn from data and make decisions without explicit programming. It works by identifying patterns in data and using them to make predictions"
Bullets:
If you're currently learning one of these, then it'll be best to go ahead and try to


In [25]:
gen_text = pipe(prompt,max_new_tokens=20,do_sample=False)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [27]:
print(gen_text[0]["generated_text"])

you are an assistant. exptract the bullet points from the following paragraph.
paragraph:"Machine Learning is a technique that allows computers to learn from data and make decisions without explicit programming. It works by identifying patterns in data and using them to make predictions"
Bullets:
"Machine Learning is a technique that allows computers to learn from data and make decisions without explicit programming.


In [29]:
prompt_1 = "I can't believe you did such a "

In [31]:
gen_text = pipe(prompt_1,max_new_tokens=20,do_sample=False)
print(gen_text[0]["generated_text"])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


I can't believe you did such a icky thing to me. I'm so sorry. I'm so sorry. I'm so sorry.


In [ ]:
### 

In [5]:
from transformers import GPT2LMHeadModel,GPT2Tokenizer
import torch

In [7]:
pretrained_model = 'gpt2'

model = GPT2LMHeadModel.from_pretrained(pretrained_model)
tokenizer = GPT2Tokenizer.from_pretrained(pretrained_model)

In [9]:
text = "The future of machine learning is"
max_length = 50

In [13]:
tokenizer.encode(text,return_tensors='pt')

tensor([[ 464, 2003,  286, 4572, 4673,  318]])

In [15]:
tokenizer.encode(text,return_tensors='tf')

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[ 464, 2003,  286, 4572, 4673,  318]], dtype=int32)>

In [17]:
tokenizer.encode(text,return_tensors='np')

array([[ 464, 2003,  286, 4572, 4673,  318]])

In [23]:
inputs = tokenizer.encode(text,return_tensors='pt')

In [37]:
def text_generation(inputs,max_length,ret_seq):
    with torch.no_grad():
        outputs = model.generate(
            inputs = inputs,
            max_length = max_length,
            num_return_sequences=ret_seq,
            no_repeat_ngram_size=2,
            top_k = 50,
            top_p = 0.95,
            do_sample=True
        )
    generated_text = [tokenizer.decode(output) for output in outputs]
    return generated_text

In [27]:
outputs

tensor([[  464,  2003,   286,  4572,  4673,   318,  6016,   351,  4572,  4430,
          2267,    11,   351,   772,   517,  7895,  4213,  2406,  1863,   284,
          1296,   649, 11798,  1390, 11666,  4430,   357, 20185,   737,   198,
           198,  5159,    25,  3012,   198,    12,   198,    13,   198,    11,
           532,   290,   198,   930,    13,   764,   198,   532, 50256]])

In [33]:
print(tokenizer.decode(outputs[0]))

The future of machine learning is bright with machine intelligence research, with even more exciting ideas coming along to form new industries including artificial intelligence (AI).

Image: Google
-
.
, - and
 |. .
 -<|endoftext|>


In [39]:
text_generation(inputs,max_length,ret_seq=1)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['The future of machine learning is now more promising," says Fincher. "The challenge is not to automate the process, but to develop an approach that will let users interact directly and to create complex information at a low cost."\n\nMachine learning']

In [41]:
text_generation(inputs,max_length,ret_seq=2)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


["The future of machine learning is not in the hands of anyone but the tech community.\n\nMachine learning, the field of computing that is now a thing of the past, has reached such a level of relevance that even Microsoft can't quite stand it",
 "The future of machine learning is a very, very interesting, fascinating field. The last ten years or so have shown us that they are, once you look at the big picture, capable of making things that can be replicated on any computer. That's"]

In [43]:
def text_generation(inputs,max_length,ret_seq,top_k,top_p):
    with torch.no_grad():
        outputs = model.generate(
            inputs = inputs,
            max_length = max_length,
            num_return_sequences=ret_seq,
            no_repeat_ngram_size=2,
            top_k = top_k,
            top_p = top_p,
            do_sample=True
        )
    generated_text = [tokenizer.decode(output) for output in outputs]
    return generated_text

In [47]:
text_generation(inputs,max_length,ret_seq=2,top_k=1,top_p=0.8)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


["The future of machine learning is in the hands of the next generation of researchers.\n\nThe next big thing is to make machine-learning algorithms more efficient and more accurate. That's what we're doing with machine vision. We're using machine intelligence",
 "The future of machine learning is in the hands of the next generation of researchers.\n\nThe next big thing is to make machine-learning algorithms more efficient and more accurate. That's what we're doing with machine vision. We're using machine intelligence"]