In [1]:
import numpy as np
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Dense,LSTM,RNN,Bidirectional,Input,SimpleRNN
from tensorflow.keras.optimizers import Adam,SGD

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (


In [3]:
seq = [10,20,30,40,50,60,70,80,90]

In [5]:
seq[:3]

[10, 20, 30]

In [7]:
seq[3]

40

In [9]:
seq[1:3+1]

[20, 30, 40]

In [11]:
seq[3+1]

50

In [ ]:
10,20,30 == > 40
20,30,40 == > 50
30,40,50 == > 60
40,50,60 == > 70

In [19]:
step_size = 3
X = []
y = []

for i in range(len(seq)):
    if step_size+i < len(seq):
        X.append(seq[i:step_size+i])
        y.append(seq[step_size+i])

In [31]:
X

[[10, 20, 30],
 [20, 30, 40],
 [30, 40, 50],
 [40, 50, 60],
 [50, 60, 70],
 [60, 70, 80]]

In [73]:
y_arr = np.array(y)

In [75]:
y_arr

array([40, 50, 60, 70, 80, 90])

In [35]:
x_arr = np.array(X)

In [ ]:
x_arr

In [41]:
x_arr.shape

(6, 3)

In [51]:
X_reshaped = x_arr.reshape(x_arr.shape[0],x_arr.shape[1],1)

In [71]:
X_reshaped

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [128]:
X_reshaped[0].shape

(3, 1)

In [57]:
SimpleRNN??

Init signature:
SimpleRNN(
    units,
    activation='tanh',
    use_bias=True,
    kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros',
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False,
    seed=None,
    **kwargs,
)
Source:        
@keras_export("keras.layers.SimpleRNN")
class SimpleRNN(RNN):
    """Fully-connected RNN where the output is to be fed back as the new input.

    Args:
        units: Positive integer, dimensionality of the output space.
        activation: Activation function to use.
            Default: hyperbolic tangent (`tanh`).
            If you pass None, no activation is applied
            (ie. "linear"

In [63]:
model = Sequential()
model.add(Input(shape=X_reshaped[0].shape))
model.add(SimpleRNN(units=256,activation='tanh',return_sequences=True,unroll=True))
model.add(Dense(16,activation='relu'))
model.add(Dense(1))

In [65]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3, 256)         │        66,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3, 16)          │         4,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3, 1)           │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 70,177 (274.13 KB)

 Trainable params: 70,177 (274.13 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.compile(optimizer="sgd",loss="mse",metrics=["accuracy"])

In [77]:
model.fit(X_reshaped,y_arr,epochs=10,verbose=1)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 0.0000e+00 - loss: 4595.5181
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0000e+00 - loss: 137742.9062
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 557582712832.0000
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0000e+00 - loss: 589343220494739290466549760.0000
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0000e+00 - loss: 235737283586209697759232.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0000e+00 - loss: 226402078163408057794560.0000
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.0000e+00 - loss: 217436582241216516587520.0000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0000e+00 - loss: 208826078056052827357184.0000
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0000e+00 - loss: 200556586434673632083968.0000
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accu

In [83]:
model = Sequential()
model.add(Input(shape=X_reshaped[0].shape))
model.add(SimpleRNN(units=256,activation='tanh',return_sequences=False,unroll=False))
model.add(Dense(16,activation='relu'))
model.add(Dense(1))

In [85]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)        │ (None, 256)            │        66,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │         4,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 70,177 (274.13 KB)

 Trainable params: 70,177 (274.13 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
LSTM??

Init signature:
LSTM(
    units,
    activation='tanh',
    recurrent_activation='sigmoid',
    use_bias=True,
    kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros',
    unit_forget_bias=True,
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    seed=None,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False,
    use_cudnn='auto',
    **kwargs,
)
Source:        
@keras_export("keras.layers.LSTM")
class LSTM(RNN):
    """Long Short-Term Memory layer - Hochreiter 1997.

    Based on available runtime hardware and constraints, this layer
    will choose different implementations (cuDNN-based or backend-native)
    to maximize the performance. If a GPU is available and all
    the

In [152]:
model = Sequential()
model.add(Input(shape=X_reshaped[0].shape))
model.add(LSTM(units=64,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(1))

In [154]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 64)             │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,953 (70.13 KB)

 Trainable params: 17,953 (70.13 KB)

 Non-trainable params: 0 (0.00 B)

In [166]:
model.compile(optimizer="adam",loss="mean_squared_error")
model.fit(X_reshaped,y_arr,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 587ms/step - loss: 1.2341
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0370
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.0365
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4797
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.2039
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9774
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.4242
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9846
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4287
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.5143
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0285
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.8815
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1412
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1402
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8568
Epoch 16/200
1/1 ━

In [168]:
Xin = np.array([70,80,90])

In [170]:
X_in_reshaped = Xin.reshape(1,3,1)

In [172]:
X_in_reshaped

array([[[70],
        [80],
        [90]]])

In [174]:
model.predict(X_in_reshaped)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[100.19256]], dtype=float32)

In [176]:
Xin = np.array([75,85,95])
X_in_reshaped = Xin.reshape(1,3,1)
X_in_reshaped


array([[[75],
        [85],
        [95]]])

In [178]:
model.predict(X_in_reshaped)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[105.35158]], dtype=float32)

#### Multilayer LSTM

In [ ]:
model = Sequential()
model.add(Input(shape=X_resh[0].shape))
model.add(LSTM(50,activation="relu",return_sequences=True))
model.add(LSTM(50,activation="relu"))
model.add(Dense(1))

model.compile(optimizer="adam",loss="mean_squared_error")
model.fit(X_resh,y,epochs=200)

#### Bidirectional LSTM

In [ ]:
model = Sequential()
model.add(Input(shape=X_resh[0].shape))
model.add(Bidirectional(LSTM(50,activation="relu")))
model.add(Dense(1))

model.compile(optimizer="Adam",loss="mse")
model.fit(X,y,epochs=200,verbose=1)