In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
from nltk import word_tokenize

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (


In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Embedding, Dense,Input,GlobalAveragePooling1D,Flatten,LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [41]:
from keras.utils import to_categorical

In [5]:
df = pd.read_csv("./data/text/synthetic_binary_sentiment_dataset_clean.csv")

In [7]:
df.head()

,sentence,emotion
0,I am impressed by how good this turned out,positive
1,I am impressed by how good this turned out,positive
2,I love this product it works perfectly,positive
3,Nothing went right horrible experience,negative
4,Nothing went right horrible experience,negative


In [13]:
df_train = pd.read_csv("./data/Covid/Corona_NLP_train.csv",encoding='latin-1')

In [15]:
df_train.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative


In [17]:
df_train["Sentiment"].value_counts()

Sentiment
Positive              11422
Negative               9917
Neutral                7713
Extremely Positive     6624
Extremely Negative     5481
Name: count, dtype: int64

In [19]:
wl = WordNetLemmatizer()
stp_wrds = stopwords.words("english")
translator = str.maketrans('','',string.punctuation)

In [21]:
def clean_text(text):
    word_tok = word_tokenize(text)
    lemma_word = [wl.lemmatize(word,pos='v') for word in word_tok if word.lower() not in stp_wrds]
    lowercase_lemma_word = [word.lower() for word in lemma_word]
    processed_text = " ".join(lowercase_lemma_word).translate(translator).strip()
    return processed_text

In [23]:
text = "Hello, World! Python is amazing."
clean_text(text)

'hello  world  python amaze'

In [25]:
df_train["Cleaned_tweet"] = df_train["OriginalTweet"].apply(lambda x:clean_text(x))

In [27]:
df_train.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment,Cleaned_tweet
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral,menyrbie philgahan chrisitv https tcoifz9fa...
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive,advice talk neighbour family exchange phone nu...
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive,coronavirus australia woolworths give elderly...
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive,food stock one empty please nt panic enough...
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative,ready go supermarket covid19 outbreak m para...


In [43]:
X = df_train["Cleaned_tweet"].values
y = df_train["Sentiment"].values

In [33]:
X[0]

'menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8'

In [35]:
X.shape

(41157,)

In [49]:
le = LabelEncoder()
y = le.fit_transform(y)

In [51]:
y

array([3, 4, 4, ..., 4, 3, 2])

In [53]:
y_train = to_categorical(y, num_classes=5)

In [55]:
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [67]:
# tokenizer = Tokenizer(num_words=10,oov_token="<OOV>")

In [143]:
tokenizer = Tokenizer(num_words=1000)

In [145]:
tokenizer.fit_on_texts(X)

In [147]:
word_index = tokenizer.word_index

In [149]:
X[0]

'menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8'

In [151]:
word_index

{'https': 1,
 'coronavirus': 2,
 'covid19': 3,
 'price': 4,
 'store': 5,
 'food': 6,
 'supermarket': 7,
 'grocery': 8,
 'people': 9,
 'amp': 10,
 'go': 11,
 'shop': 12,
 '19': 13,
 'consumer': 14,
 'get': 15,
 'covid': 16,
 'need': 17,
 's': 18,
 'online': 19,
 'buy': 20,
 'pandemic': 21,
 'time': 22,
 'work': 23,
 'hand': 24,
 'us': 25,
 'workers': 26,
 'help': 27,
 'stock': 28,
 'panic': 29,
 'make': 30,
 'nt': 31,
 'like': 32,
 'home': 33,
 'sanitizer': 34,
 'demand': 35,
 'say': 36,
 'take': 37,
 'see': 38,
 'supply': 39,
 'one': 40,
 'due': 41,
 'keep': 42,
 'mask': 43,
 'oil': 44,
 'new': 45,
 'please': 46,
 'stay': 47,
 'covid2019': 48,
 'use': 49,
 'crisis': 50,
 'toiletpaper': 51,
 'market': 52,
 'toilet': 53,
 'retail': 54,
 'think': 55,
 'paper': 56,
 'local': 57,
 'know': 58,
 'today': 59,
 'via': 60,
 'many': 61,
 'still': 62,
 'increase': 63,
 'shelve': 64,
 'delivery': 65,
 'stop': 66,
 '2': 67,
 'come': 68,
 'spread': 69,
 'impact': 70,
 'close': 71,
 'would': 72,
 'loc

In [153]:
sequences = tokenizer.texts_to_sequences(X)

In [155]:
sequences

[[1, 1, 1],
 [451,
  327,
  203,
  654,
  316,
  354,
  341,
  237,
  654,
  316,
  439,
  373,
  19,
  12,
  841,
  39,
  941,
  87],
 [2, 673, 93, 263, 12, 201, 99, 3, 79, 1],
 [6,
  28,
  40,
  144,
  46,
  31,
  29,
  189,
  6,
  85,
  37,
  17,
  47,
  827,
  47,
  106,
  3,
  3,
  2,
  1],
 [647,
  11,
  7,
  3,
  79,
  163,
  6,
  28,
  144,
  2,
  739,
  252,
  46,
  31,
  29,
  183,
  375,
  302,
  1],
 [133,
  125,
  794,
  3,
  188,
  68,
  746,
  128,
  98,
  9,
  532,
  5,
  268,
  278,
  39,
  24,
  34,
  6,
  53,
  56,
  234,
  112,
  1],
 [582, 8, 5, 170, 679, 3, 163, 957, 58, 163, 327, 1],
 [7, 59, 31, 20, 53, 56, 728, 3, 1],
 [41,
  3,
  54,
  5,
  109,
  91,
  957,
  185,
  190,
  155,
  361,
  717,
  197,
  148,
  854,
  19,
  654,
  87,
  342,
  77,
  410,
  1],
 [142,
  66,
  20,
  187,
  509,
  49,
  19,
  142,
  69,
  696,
  89,
  19,
  12,
  33,
  18,
  22,
  158,
  16,
  13],
 [418, 31, 547, 152, 384, 765, 225, 201, 71, 224, 85, 49, 709, 7, 73, 48, 1],
 [41, 3

In [157]:
X_train = pad_sequences(sequences, maxlen=50, padding='post')

In [159]:
X_train[0].shape

(50,)

In [161]:
vocab_size = len(word_index)+1
embedding_dim = 16
max_len = 10

In [163]:
vocab_size

81628

In [175]:
model = Sequential()
model.add(Input(shape = X_train[0].shape))
model.add(Embedding(input_dim = 1000,output_dim=embedding_dim))
model.add(GlobalAveragePooling1D())
model.add(Dense(32,activation="relu"))
model.add(Dense(16,activation="relu"))
model.add(Dense(5,activation="softmax"))

In [177]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 50, 16)         │     1,306,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_2      │ (None, 16)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 5)              │            85 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,307,205 (4.99 MB)

 Trainable params: 1,307,205 (4.99 MB)

 Non-trainable params: 0 (0.00 B)

In [173]:
16000/17157

0.9325639680596841

In [169]:
model.compile(optimizer="sgd",loss="categorical_crossentropy",metrics=["accuracy"])

In [171]:
model.fit(X_train,y_train,epochs=20,verbose=1)

Epoch 1/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 1s 275us/step - accuracy: 0.2725 - loss: 1.5882
Epoch 2/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.2727 - loss: 1.5763
Epoch 3/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 266us/step - accuracy: 0.2775 - loss: 1.5701
Epoch 4/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - accuracy: 0.2774 - loss: 1.5694
Epoch 5/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.2754 - loss: 1.5681
Epoch 6/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.2753 - loss: 1.5604
Epoch 7/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.2805 - loss: 1.5542
Epoch 8/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.2983 - loss: 1.5434
Epoch 9/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.3065 - loss: 1.5316
Epoch 10/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - accuracy: 0.3079 - loss: 1.5243
Epoch 11/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - accuracy: 0.3066 - loss: 1.5213
Epoch 12

In [179]:
df_test = pd.read_csv("./data/Covid/Corona_NLP_test.csv")

In [181]:
df_test.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,TRENDING: New Yorkers encounter empty supermar...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,When I couldn't find hand sanitizer at Fred Me...,Positive
2,3,44955,NaN,02-03-2020,Find out how you can protect yourself and love...,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,#Panic buying hits #NewYork City as anxious sh...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,#toiletpaper #dunnypaper #coronavirus #coronav...,Neutral


In [191]:
text = df_test["OriginalTweet"][0]

In [193]:
text

'TRENDING: New Yorkers encounter empty supermarket shelves (pictured, Wegmans in Brooklyn), sold-out online grocers (FoodKick, MaxDelivery) as #coronavirus-fearing shoppers stock up https://t.co/Gr76pcrLWh https://t.co/ivMKMsqdT1'

In [195]:
cleaned_text = clean_text(text)

In [197]:
cleaned_text

'trending  new yorkers encounter empty supermarket shelve  picture  wegmans brooklyn   soldout online grocers  foodkick  maxdelivery   coronavirusfearing shoppers stock https  tcogr76pcrlwh https  tcoivmkmsqdt1'

In [203]:
test_sequences = tokenizer.texts_to_sequences([cleaned_text])

In [205]:
test_sequences

[[45, 144, 7, 64, 875, 19, 281, 28, 1, 1]]

In [207]:
padded_test_seq = pad_sequences(test_sequences, maxlen=50, padding='post')

In [209]:
padded_test_seq

array([[ 45, 144,   7,  64, 875,  19, 281,  28,   1,   1,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int32)

In [213]:
y_pred = model.predict(padded_test_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


In [217]:
y_pred.sum()

1.0

In [221]:
y_pred

array([[0.20240812, 0.20137554, 0.2010356 , 0.1961286 , 0.19905207]],
      dtype=float32)

In [219]:
np.argmax(y_pred)

0

In [229]:
le.inverse_transform([0])

array(['Extremely Negative'], dtype=object)